// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAaylufwJMWiFP-j55Fdxvwa4ee0_kkUE',
    appId: '1:301125166728:web:e73a1d911ef63137c7e13d',
    messagingSenderId: '301125166728',
    projectId: 'flutter-app-citas',
    authDomain: 'flutter-app-citas.firebaseapp.com',
    storageBucket: 'flutter-app-citas.firebasestorage.app',
    measurementId: 'G-335SVCXYW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxQ4vc5jM0pZSBIU9gPrpzZPPE98volI8',
    appId: '1:301125166728:android:612a8b713c3531ddc7e13d',
    messagingSenderId: '301125166728',
    projectId: 'flutter-app-citas',
    storageBucket: 'flutter-app-citas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnn34M2Hj2gg2qdZJjXOW7PRg7VebakYg',
    appId: '1:301125166728:ios:f811a49b69b328c0c7e13d',
    messagingSenderId: '301125166728',
    projectId: 'flutter-app-citas',
    storageBucket: 'flutter-app-citas.firebasestorage.app',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnn34M2Hj2gg2qdZJjXOW7PRg7VebakYg',
    appId: '1:301125166728:ios:f811a49b69b328c0c7e13d',
    messagingSenderId: '301125166728',
    projectId: 'flutter-app-citas',
    storageBucket: 'flutter-app-citas.firebasestorage.app',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAaylufwJMWiFP-j55Fdxvwa4ee0_kkUE',
    appId: '1:301125166728:web:671f00294ea755f4c7e13d',
    messagingSenderId: '301125166728',
    projectId: 'flutter-app-citas',
    authDomain: 'flutter-app-citas.firebaseapp.com',
    storageBucket: 'flutter-app-citas.firebasestorage.app',
    measurementId: 'G-VD8S7ZBXFN',
  );

}